const actionTypes = {
  CHANGE_ACTIVE_TAB: 'CONFIG/CHANGE_ACTIVE_TAB',
  CHANGE_PREVIEW_MODE: 'CONFIG/CHANGE_PREVIEW_MODE',
  SET_SELECTED_BLOCK: 'LAYOUT/SET_SELECTED_BLOCK',
  PUSH_BLOCK: 'LAYOUT/PUSH_BLOCK',
  CHANGE_BLOCK_DATA: 'LAYOUT/CHANGE_BLOCK_DATA',
  REORDER_LAYOUT: 'LAYOUT/REORDER_LAYOUT',
  DELETE_BLOCK: 'LAYOUT/DELETE_BLOCK',
  CHANGE_DOCUMENT_ID: 'LAYOUT/CHANGE_DOCUMENT_ID',
  SAVE_BLOCKS_DATA: 'LAYOUT/SAVE_BLOCKS_DATA',
  RETRIVE_BLOCK_DATA: 'LAYOUT/RETRIVE_BLOCK_DATA',
  HYDRATE_REDUX_STATE: 'LAYOUT/HYDRATE_REDUX_STATE',
  RESET_BLOCK_DATA: 'LAYOUT/RESET_BLOCK_DATA',
  DELETE_FILE: 'LAYOUT/DELETE_FILE',

};

export default actionTypes;
